name: Check Code Lint & test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        npm i
        npm i -g eslint
        pwd
    - name: Run ESLint
      run: npm run lint
    - name: Run Tests
      run: npm run test

